
let a = document.getElementById("checkbox");
a.addEventListener('click', ()=>{
    if(a.checked === true){
        document.getElementById("adal").style.backgroundColor = "Black"
    }
    else{
        document.getElementById("adal").style.backgroundColor = "#fff" 
    }
});
let b = document.getElementById("checkbox");
b.addEventListener('click', ()=>{
    if(b.checked ===true){
        document.getElementById("dark").style.color = "red"
        document.getElementById("dark2").style.color = "#fff"
        document.getElementById("dark3").style.color = "#fff"
        document.getElementById("dark4").style.color = "#fff"
        document.getElementById("dark5").style.color = "#fff"
        document.getElementById("dark6").style.color = "#fff"
        document.getElementById("dark7").style.color = "#fff"
        document.getElementById("dark8").style.color = "#fff"
        document.getElementById("dark9").style.color = "#fff"
        document.getElementById("dark10").style.color = "#fff"
        document.getElementById("border").style.borderColor = "gray"
        document.getElementById("ul-list").style.backgroundColor = "rgba(0, 0, 0, 0.884)"
        document.getElementById("icon").style.color = "red"
        document.getElementById("nav").style.backgroundColor = "Black"
    }
    else{
        document.getElementById("dark").style.color = "Blue"
        document.getElementById("dark2").style.color = "darkblue"
        document.getElementById("dark3").style.color = "darkblue"
        document.getElementById("dark4").style.color = "darkblue"
        document.getElementById("dark5").style.color = "darkblue"
        document.getElementById("dark6").style.color = "Black"
        document.getElementById("dark7").style.color = "Black"
        document.getElementById("dark8").style.color = "Black"
        document.getElementById("dark10").style.color = "Black"
        document.getElementById("border").style.borderColor = "blueviolet"
        document.getElementById("ul-list").style.backgroundColor = "rgba(255, 255, 255, 0.955)"
        document.getElementById("icon").style.color = "Blue"
       document.getElementById("nav").style.backgroundColor = "#fff"
    }
});

let k = document.getElementById("checkbox");
k.addEventListener('click', ()=>{
    if(k.checked === true){
        document.getElementById("red").style.color = "#fff"
        document.getElementById("dark11").style.color = "#fff"
        document.getElementById("dark12").style.color = "#fff"
        document.getElementById("about").style.color = "yellow"
        document.getElementById("skill").style.color = "yellow"
        document.getElementById("red2").style.color = "#fff"
        document.getElementById("red3").style.color = "#fff"
        document.getElementById("red4").style.color = "#fff"
        document.getElementById("red5").style.color = "#fff"
        document.getElementById("red6").style.color = "#fff"
        document.getElementById("red7").style.color = "#fff"
        document.getElementById("dark13").style.color = "#fff"
        document.getElementById("dark14").style.color = "#fff"
        document.getElementById("dark15").style.color = "#fff"
        document.getElementById("dark16").style.color = "#fff"
        document.getElementById("dark17").style.color = "#fff"
        document.getElementById("dark18").style.color = "#fff"
        document.getElementById("dark19").style.color = "#fff"
        document.getElementById("dark20").style.color = "#fff"
        document.getElementById("dark21").style.color = "#fff"
        document.getElementById("dark22").style.color = "#fff"
        document.getElementById("dark23").style.color = "#fff"
        document.getElementById("dark24").style.color = "#fff"
        document.getElementById("dark25").style.color = "#fff"
        document.getElementById("dark26").style.color = "#fff"
        document.getElementById("dark27").style.color = "#fff"
        document.getElementById("dark28").style.color = "#fff"
        document.getElementById("dark29").style.color = "#fff"
        document.getElementById("dark30").style.color = "#fff"
        document.getElementById("dark31").style.color = "#fff"
        document.getElementById("dark32").style.color = "#fff"
        document.getElementById("ul-list2").style.backgroundColor = "rgba(0, 0, 0, 0.884)"
        document.getElementById("nav2").style.backgroundColor = "Black"
        document.getElementById("icon2").style.color = "red"
    }
    else{
        document.getElementById("red").style.color = "Black"
        document.getElementById("dark11").style.color = "Black"
        document.getElementById("dark12").style.color = "Black"
        document.getElementById("about").style.color = "purple"
        document.getElementById("skill").style.color = "purple"
        document.getElementById("red2").style.color = "Black"
        document.getElementById("red3").style.color = "Black"
        document.getElementById("red4").style.color = "Black"
        document.getElementById("red5").style.color = "Black"
        document.getElementById("red6").style.color = "Black"
        document.getElementById("red7").style.color = "Black"
        document.getElementById("dark13").style.color = "darkblue"
        document.getElementById("dark14").style.color = "darkblue"
        document.getElementById("dark15").style.color = "darkblue"
        document.getElementById("dark16").style.color = "darkblue"
        document.getElementById("dark17").style.color = "darkblue"
        document.getElementById("dark18").style.color = "darkblue"
        document.getElementById("dark19").style.color = "darkblue"
        document.getElementById("dark20").style.color = "darkblue"
        document.getElementById("dark21").style.color = "darkblue"
        document.getElementById("dark22").style.color = "darkblue"
        document.getElementById("dark23").style.color = "darkblue"
        document.getElementById("dark24").style.color = "darkblue"
        document.getElementById("dark25").style.color = "darkblue"
        document.getElementById("dark26").style.color = "darkblue"
        document.getElementById("dark27").style.color = "darkblue"
        document.getElementById("dark28").style.color = "darkblue"
        document.getElementById("dark29").style.color = "darkblue"
        document.getElementById("dark30").style.color = "darkblue"
        document.getElementById("dark31").style.color = "darkblue"
        document.getElementById("dark32").style.color = "darkblue"
         document.getElementById("ul-list2").style.backgroundColor = "rgba(255, 255, 255, 0.955)"
          document.getElementById("nav2").style.backgroundColor = "#fff"
           document.getElementById("icon2").style.color = "Blue"
    }
});
d = document.getElementById("checkbox");
d.addEventListener('click', ()=>{
    if(d.checked ===true){
        document.getElementById("dark33").style.color = "#fff"
        document.getElementById("dark34").style.color = "#fff"
        document.getElementById("dark35").style.color = "#fff"
        document.getElementById("dark36").style.color = "#fff"
        document.getElementById("dark37").style.color = "#fff"
        document.getElementById("dark38").style.color = "#fff"
        document.getElementById("dark39").style.color = "#fff"
        document.getElementById("dark40").style.color = "#fff"
        document.getElementById("dark41").style.color = "#fff"
        document.getElementById("dark42").style.color = "#fff"
        document.getElementById("dark43").style.color = "#fff"
        document.getElementById("dark44").style.color = "#fff"
        document.getElementById("dark45").style.color = "#fff"
        document.getElementById("dark46").style.color = "#fff"
        document.getElementById("dark47").style.color = "#fff"
        document.getElementById("dark48").style.color = "#fff"
        document.getElementById("dark49").style.color = "#fff"
        document.getElementById("dark50").style.color = "#fff"
         document.getElementById("ul-list3").style.backgroundColor = "rgba(0, 0, 0, 0.884)"
        document.getElementById("nav3").style.backgroundColor = "Black"
        document.getElementById("icon3").style.color = "red"
    }
    else{
        document.getElementById("dark33").style.color = "Black"
        document.getElementById("dark34").style.color = "Black"
        document.getElementById("dark35").style.color = "Black"
        document.getElementById("dark36").style.color = "Black"
        document.getElementById("dark37").style.color = "Black"
        document.getElementById("dark38").style.color = "Black"
        document.getElementById("dark39").style.color = "Black"
        document.getElementById("dark40").style.color = "Black"
        document.getElementById("dark41").style.color = "Black"
        document.getElementById("dark42").style.color = "Black"
        document.getElementById("dark43").style.color = "Black"
        document.getElementById("dark44").style.color = "Black"
        document.getElementById("dark45").style.color = "Black"
        document.getElementById("dark46").style.color = "Black"
        document.getElementById("dark47").style.color = "Black"
        document.getElementById("dark48").style.color = "Black"
        document.getElementById("dark49").style.color = "Black"
        document.getElementById("dark50").style.color = "Black"
        document.getElementById("ul-list3").style.backgroundColor = "rgba(255, 255, 255, 0.955)"
          document.getElementById("nav3").style.backgroundColor = "#fff"
          document.getElementById("icon3").style.color = "Blue"
    }
});
l = document.getElementById("checkbox");
l.addEventListener('click', () =>{
    if(l.checked === true){
        document.getElementById("dark51").style.color = "#fff"
        document.getElementById("dark52").style.color = "#fff"
        document.getElementById("dark53").style.color = "#fff"
        document.getElementById("dark54").style.color = "#fff"
        document.getElementById("dark55").style.color = "#fff"
        document.getElementById("dark56").style.color = "#fff"
        document.getElementById("ul-list4").style.backgroundColor = "rgba(0, 0, 0, 0.884)"
        document.getElementById("nav4").style.backgroundColor = "Black"
        document.getElementById("icon4").style.color = "red"
    }
    else{
        document.getElementById("dark51").style.color = "Black"
        document.getElementById("dark52").style.color = "Black"
        document.getElementById("dark53").style.color = "Black"
        document.getElementById("dark54").style.color = "Black"
        document.getElementById("dark55").style.color = "Black"
        document.getElementById("dark56").style.color = "Black"
        document.getElementById("ul-list4").style.backgroundColor = "rgba(255, 255, 255, 0.955)"
        document.getElementById("nav4").style.backgroundColor = "#fff"
        document.getElementById("icon4").style.color = "Blue"
    }
});
m = document.getElementById("checkbox");
m.addEventListener('click', ()=>{
    if(m.checked ===true){
        document.getElementById("cv1").style.color = "yellow"
        document.getElementById("element").style.color = "yellow"
        document.getElementById("cv2").style.color = "#fff"
        document.getElementById("cv3").style.color = "#fff"
        document.getElementById("cv4").style.color = "#fff"
        document.getElementById("cv5").style.color = "#fff"
        document.getElementById("cv6").style.color = "#fff"
        document.getElementById("cv7").style.color = "#fff"
        document.getElementById("cv8").style.color = "#fff"
        document.getElementById("cv9").style.color = "#fff"
        document.getElementById("cv10").style.color = "#fff"
        document.getElementById("cv11").style.color = "#fff"
        document.getElementById("cv12").style.color = "#fff"
        document.getElementById("cv13").style.color = "#fff"
        document.getElementById("cv14").style.color = "#fff"
        document.getElementById("cv15").style.color = "#fff"
        document.getElementById("ul-list5").style.backgroundColor = "rgba(0, 0, 0, 0.884)"
        document.getElementById("nav5").style.backgroundColor = "Black"
        document.getElementById("icon5").style.color = "red"
    }
    else{
         document.getElementById("cv1").style.color = "blueviolet"
         document.getElementById("element").style.color = "blueviolet"
         document.getElementById("cv2").style.color = "Black"
         document.getElementById("cv3").style.color = "Black"
         document.getElementById("cv4").style.color = "Black"
         document.getElementById("cv5").style.color = "Black"
         document.getElementById("cv6").style.color = "Black"
         document.getElementById("cv7").style.color = "Black"
         document.getElementById("cv8").style.color = "Black"
         document.getElementById("cv9").style.color = "Black"
         document.getElementById("cv10").style.color = "Black"
         document.getElementById("cv11").style.color = "Black"
         document.getElementById("cv12").style.color = "Black"
         document.getElementById("cv13").style.color = "Black"
         document.getElementById("cv14").style.color = "Black"
         document.getElementById("cv15").style.color = "Black"
         document.getElementById("ul-list5").style.backgroundColor = "rgba(255, 255, 255, 0.955)"
        document.getElementById("nav5").style.backgroundColor = "#fff"
        document.getElementById("icon5").style.color = "Blue"
    }
});
p = document.getElementById("checkbox");
p.addEventListener('click', ()=>{
    if(p.checked ===true){
        document.getElementById("khan1").style.color = "#fff"
        document.getElementById("khan2").style.color = "#fff"
        document.getElementById("khan3").style.color = "#fff"
        document.getElementById("khan4").style.color = "#fff"
        document.getElementById("khan5").style.color = "#fff"
        document.getElementById("khan6").style.color = "#fff"
        document.getElementById("khan7").style.color = "#fff"
        document.getElementById("khan8").style.color = "#fff"
        document.getElementById("khan9").style.color = "#fff"
        document.getElementById("khan10").style.color = "#fff"
        document.getElementById("khan11").style.color = "#fff"
        document.getElementById("khan12").style.color = "#fff"
        document.getElementById("khan13").style.color = "#fff"
        document.getElementById("khan14").style.color = "#fff"
        document.getElementById("khan15").style.color = "#fff"
         document.getElementById("ul-list-2").style.backgroundColor = "rgba(0, 0, 0, 0.884)"
         document.getElementById("icon-2").style.color = "red"
    }
    else{
        document.getElementById("khan1").style.color = "darkblue"
        document.getElementById("khan2").style.color = "darkblue"
        document.getElementById("khan4").style.color = "darkblue"
        document.getElementById("khan3").style.color = "darkblue"
        document.getElementById("khan5").style.color = "darkblue"
        document.getElementById("khan6").style.color = "darkblue"
        document.getElementById("khan7").style.color = "darkblue"
        document.getElementById("khan8").style.color = "darkblue"
        document.getElementById("khan9").style.color = "darkblue"
        document.getElementById("khan10").style.color = "darkblue"
        document.getElementById("khan11").style.color = "darkblue"
        document.getElementById("khan12").style.color = "darkblue"
        document.getElementById("khan13").style.color = "darkblue"
        document.getElementById("khan14").style.color = "darkblue"
        document.getElementById("khan15").style.color = "darkblue"
        document.getElementById("ul-list-2").style.backgroundColor = "rgba(255, 255, 255, 0.955)"
         document.getElementById("icon-2").style.color = "Blue"
    }
})